### ISSUE TITLE
misc_bsp support

### ISSUE THREAD

**Issue by mheh** [thecybermind/stripper_qmm#1]
Hey TheCyberMind,

I suck at programming but I enjoy learning.  I'm trying to fix the stripper add-on.  When you place a misc_bsp on any map stripper will fail to load the map and trigger a shutdown.

I've been placing text printouts of what's happening into the log files and when it's building the entities and reaches, i suppose, the misc_bsp entity it fails and says SpawnEntities: No entities.

I'll keep working on understanding how the lists are built and how misc_bsp could be affecting it but if you have input that would be appreciated.  Works like a charm otherwise!

Thanks

**Comment by thecybermind** [comment]
Hi! 

That error message only appears when the game mod doesn't receive any entities from the engine. It appears like Jedi Academy calls the function which pulls these entities once it loads another map file due to misc_bsp. Since stripper_qmm only loads entities at map load, and then provides them to the mod when it runs its own load event, it looks like stripper_qmm needs to handle the subsequent requests for more entity info.

I've been familiarizing myself with the code in the Jedi Academy SDK and I can let you know what I find.

**Comment by thecybermind** [comment]
Hey @mheh !

Please try the latest version (v1.2.1). Just to be sure it works, I have added a check which should hopefully allow the map to load properly, but currently it will do no adding/editing/removing for any entities that exist on the misc_bsp that is loaded.

**Comment by mheh** [comment]
Yep! It works, maps load within maps!

Thanks so much man! I checked the commit history and it's awesome seeing what you did.
